### ISSUE TITLE
wrong type for arrays

### ISSUE THREAD

**Issue by farzonl** [afshawnlotfi/jsontosharp#1]
{
"foo":[1,2,3]
}

wrong type assigned should be array but got object, if all types are the same maybe infer type so in this case int array.

**Comment by farzonl** [comment]
If this is for c# then you should not assume js type system for c#, check objects with  [Array.isArray()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) then if you want check the array fields to infer type.

**Comment by afshawnlotfi** [comment]
Fixed
